# Conexión a la BDD
spring.datasource.url: jdbc:mysql://db.ctd.academy:3306/1023c07_GRUPO4
spring.datasource.username: 1023c07_GRUPO4
spring.datasource.password: Fahxed2v
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: true
server.port: 3306

image.upload.path: https://s3.console.aws.amazon.com/s3/buckets/1023c

# Conexión a la S3
s3.access-key: AKIAY3PLHSUJMQAM2NK3
s3.secret-key: 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
s3.bucket-name: 1023c07-grupo4
s3.region: us-east-1